### ISSUE TITLE
모임 생성

### ISSUE THREAD

**Issue by ro-el-c** [KUIT-CoNet/CoNet-Server#1]
### 상세 내용
모임을 생성(DB에 첫 등록)하는 기능
초대 코드는 랜덤으로 생성되는 문자열 - 영문 대소문자, 숫자 포함하여 8자 정도

### ToDo
- [x] 모임 참여 방식 결정하기
- [x] 초대 코드 생성 구현
    - [x] 초대코드 중복 확인
- [x] DB update
    - [x] 초대코드 update
    - [x] 초대 코드 생성 시간 - timestamp update
    - [x] teamMember table update 
- [x] API 구현 마무리
- [ ] API 테스트
