### ISSUE TITLE
회원 탈퇴

### ISSUE THREAD

**Issue by ro-el-c** [KUIT-CoNet/CoNet-Server#24]
### 상세 내용
회원 탈퇴 기능

### ToDo
- [x] user table의 platform, platfomrId, serviceTerm 초기화
- [x] 참여한 모든 group(모임)에 대하여 status를 0으로 변경
- [x] API 구현 마무리
- [x] API 테스트
