### ISSUE TITLE
프로필 사진 변경 API 수정

### ISSUE THREAD

**Issue by ro-el-c** [KUIT-CoNet/CoNet-Server#46]
## 회원 정보 수정 API 수정

기존 프로필 이미지 데이터 삭제 및 새로운 이미지 업로드
DB 업데이트

### ToDo
- [x] 기존 프로필 이미지 S3에서 삭제
- [x] 새로운 이미지 S3에 업로드
- [x] DB에 새로운 이미지 url 업데이트
- [x] API 테스트
- [x] s3에 없는 객체 삭제 요청했을 때에 대한 validation 처리
