### ISSUE TITLE
S3 조회 및 삭제 유효성 검사

### ISSUE THREAD

**Issue by ro-el-c** [KUIT-CoNet/CoNet-Server#52]
### 상세 내용

AWS S3 사용에 따른 유효성 검사 추가

### ToDo
- [x] 프로필 이미지 변경 api 수정
  - [x] s3에 없는 객체 삭제 요청했을 때에 대한 validation 처리
    - [x] 객체 삭제 생략
- [x] 회원 정보 조회 api 수정
  - [x] s3에 없는 객체 요청했을 때에 대한 validation 처리
    - [x] 기본 이미지로 변경
