### ISSUE TITLE
AWS S3 업로드 확장자명 수정

### ISSUE THREAD

**Issue by ro-el-c** [KUIT-CoNet/CoNet-Server#56]
### 상세 내용
".png"로 고정했던 fileName 생성 과정 수정
- 받은 파일의 확장자로 수정

받은 파일의 content type이 image가 아닌 경우 Exception
<br>

### ToDo
- [x] image type 유효성 검사 추가
- [x] 확장자명 처리 과정 수정
- [x] 기존 이미지 삭제 과정에서 이미지 타입 검사가 먼저 수행되도록 로직 수정
